<?php
/**
 * NexUse — database connection.
 *
 * MVC layer: Core. Wraps PDO so Models never build a connection themselves.
 */

declare(strict_types=1);

namespace App\Core;

use PDO;
use PDOException;
use PDOStatement;

class Database
{
    private static ?PDO $connection = null;

    /**
     * The shared PDO connection, opened on first use.
     */
    public static function connection(): PDO
    {
        if (self::$connection === null) {
            $config = Config::all();

            $dsn = sprintf(
                'mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',
                $config['db_host'],
                (int) $config['db_port'],
                $config['db_name']
            );

            try {
                self::$connection = new PDO($dsn, $config['db_user'], $config['db_pass'], [
                    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    PDO::ATTR_EMULATE_PREPARES   => false,
                ]);
            } catch (PDOException $e) {
                http_response_code(500);

                if (Config::get('debug')) {
                    exit('Database connection failed: ' . $e->getMessage());
                }

                exit('Database connection failed. Check that MySQL is running.');
            }
        }

        return self::$connection;
    }

    /**
     * Run a prepared statement.
     *
     * @param array<int|string, mixed> $params
     */
    public static function run(string $sql, array $params = []): PDOStatement
    {
        $statement = self::connection()->prepare($sql);
        $statement->execute($params);

        return $statement;
    }

    /**
     * Fetch a single row, or null.
     *
     * @param  array<int|string, mixed> $params
     * @return array<string, mixed>|null
     */
    public static function one(string $sql, array $params = []): ?array
    {
        $row = self::run($sql, $params)->fetch();

        return $row === false ? null : $row;
    }

    /**
     * Fetch every matching row.
     *
     * @param  array<int|string, mixed> $params
     * @return list<array<string, mixed>>
     */
    public static function all(string $sql, array $params = []): array
    {
        return self::run($sql, $params)->fetchAll();
    }

    /**
     * Fetch one scalar value.
     *
     * @param array<int|string, mixed> $params
     */
    public static function value(string $sql, array $params = [], mixed $default = null): mixed
    {
        $value = self::run($sql, $params)->fetchColumn();

        return $value === false ? $default : $value;
    }

    /**
     * The id generated by the last INSERT.
     */
    public static function lastId(): int
    {
        return (int) self::connection()->lastInsertId();
    }

    public static function begin(): void
    {
        self::connection()->beginTransaction();
    }

    public static function commit(): void
    {
        self::connection()->commit();
    }

    public static function rollBack(): void
    {
        if (self::connection()->inTransaction()) {
            self::connection()->rollBack();
        }
    }
}
